### ISSUE TITLE
Cannot use array type return in doc/lit operation

### ISSUE THREAD

**Issue by tdiesler** [jboss-fuse/wsdl2rest#6]
```java
@WebService
@SOAPBinding(style = Style.DOCUMENT)
public interface Address {

    /**
     * List the available resource ids.
     */
    @WebMethod
    Integer[] listAddresses();
    ...
}
```

```
Running org.slosc.wsdl2rest.test.doclit.CamelCxfWsDocLitTest
- No Server set for org.apache.cxf.transport.http_jetty.JettyHTTPServerEngine$1@72456279
- Interceptor for {http://doclit.test.wsdl2rest.slosc.org/}AddressService#{http://doclit.test.wsdl2rest.slosc.org/}listAddresses has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: java.lang.Integer cannot be cast to [Ljava.lang.Integer;
	at org.apache.cxf.jaxws.interceptors.WrapperClassOutInterceptor.handleMessage(WrapperClassOutInterceptor.java:107)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:278)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:78)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.doService(JettyHTTPDestination.java:234)
	at org.apache.cxf.transport.http_jetty.JettyHTTPHandler.handle(JettyHTTPHandler.java:70)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1129)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1065)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:189)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handleAsync(Server.java:549)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to [Ljava.lang.Integer;
	at org.slosc.wsdl2rest.test.doclit.jaxws_asm.ListAddressesResponse_WrapperTypeHelper1.createWrapperObject(Unknown Source)
	at org.apache.cxf.jaxws.interceptors.WrapperClassOutInterceptor.handleMessage(WrapperClassOutInterceptor.java:91)
	... 20 more
```

**Comment by tdiesler** [comment]
Done
