### ISSUE TITLE
"Cannot obtain java method" error

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/wsdl2rest#60]
```
java.lang.IllegalStateException: Cannot obtain java method for: Add
--
at org.jboss.fuse.wsdl2rest.util.IllegalStateAssertion.assertNotNull(IllegalStateAssertion.java:50)
at org.jboss.fuse.wsdl2rest.impl.codegen.CamelContextGenerator.getJavaMethod(CamelContextGenerator.java:121)
at org.jboss.fuse.wsdl2rest.impl.codegen.CamelContextGenerator.addTypeMapping(CamelContextGenerator.java:94)
at org.jboss.fuse.wsdl2rest.impl.codegen.CamelContextGenerator.process(CamelContextGenerator.java:76)
at org.jboss.fuse.wsdl2rest.impl.Wsdl2Rest.process(Wsdl2Rest.java:92)
at org.fusesource.ide.wsdl2rest.ui.wizard.Wsdl2RestWizard.generate(Wsdl2RestWizard.java:323)
at org.fusesource.ide.wsdl2rest.ui.wizard.Wsdl2RestWizard.access$0(Wsdl2RestWizard.java:286)
at org.fusesource.ide.wsdl2rest.ui.wizard.Wsdl2RestWizard$1.run(Wsdl2RestWizard.java:112)
```

see more details on https://issues.jboss.org/browse/FUSETOOLS-3091 (includign the wsdl to reproduce)

**Comment by bfitzpat** [comment]
Created PR - https://github.com/jboss-fuse/wsdl2rest/pull/63

**Comment by bfitzpat** [comment]
All fixes merged
